data_method: MyReports.personal_cards
chart:
  options:
    maintainAspectRatio: true
    scales:
      xAxes:
      - scaleLabel:
          display: true
          labelString: Rok
        stacked: true
      yAxes:
      - scaleLabel:
          display: true
          labelString: Liczba wpisów
        stacked: true
